#!/bin/sh -eu

LOCATION=`(readlink "$0" || printf "%s" "$0") | xargs dirname`

printf "project name (lower case, '-' separated): "
read pin

printf "project category (hackage category): "
read Network APIs

printf "project desc (single sentence decription): "
read Library for pin.net.au HTTP Api

printf "project namespace (camel case, '.' separated): "
read Pin

printf "github account name: "
read ApiEngine

Pin="`echo $Pin | sed -e 's:\.:/:g'`"
set -- sed -e "s:pin:$pin:g" -e "s:Pin:$Pin:g" -e "s:Library for pin.net.au HTTP Api:$Library for pin.net.au HTTP Api:g" -e "s:Pin:$Pin:g" -e "s:ApiEngine:$ApiEngine:g" -e "s:Network APIs:$Network APIs:g"

# file renames
find "$LOCATION" -type f | while read d; do
   target=`echo "$d" | "$@"`
   [ "$target" = "$d" ] || {
     target_dir=`dirname $target`
     target_file=`basename $target`
     mkdir -p "$target_dir"
     mv "$d" "$target_dir/$target_file" 
   }
done

# directory renames
find "$LOCATION" -type d | while read d; do
   target=`echo "$d" | "$@"`
   [ "$target" = "$d" ] || {
     target_dir=`dirname $target`
     target_file=`basename $target`
     mkdir -p "$target_dir"
     mv "$d" "$target_dir/$target_file" 
   }
done

# content renames
find "$LOCATION" -type f | while read f; do
    mv "$f" "$f.bak"
    "$@" < "$f.bak" > "$f" && rm "$f.bak"
done

# tweak readme
rm "$LOCATION/README.md"
mv "$LOCATION/README" "$LOCATION/README.md"
rm -rf "$LOCATION/.git"
(cd $LOCATION && git init && git add . && git commit -m "initial commit created by template")
